// src/app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import type { ReactNode } from "react";
import { Header } from "./components/Structure/Header";
import { Footer } from "./components/Structure/Footer";
import { PlannerProvider } from "./context/PlannerContext";

interface LayoutProps {
  children: ReactNode;
}

const inter = Inter({ subsets: ["latin"] });

// SEO
export const metadata: Metadata = {
  title: "Travian World",
  description: "Generated by create next app",
  icons: {
    icon: "/logo1.svg", // Ссылка на иконку в папке public
    shortcut: "/logo1.svg", // Для поддержки разных браузеров
    apple: "/logo1.svg", // Альтернативная иконка для устройств Apple
  },
};

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PlannerProvider>
          <div id="__next" className="flex min-h-screen flex-col">
            <Header />
            <main className="flex flex-1 flex-row justify-between mx-[0px] my-[0px]">
              {children}
            </main>
            <Footer />
          </div>
        </PlannerProvider>
      </body>
    </html>
  );
}
